# Generated by Django 5.2.5 on 2025-08-31 16:29

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("health_worker", "Health Worker"),
                            ("citizen", "Citizen"),
                        ],
                        default="citizen",
                        max_length=20,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
                ),
                ("email_verified", models.BooleanField(default=False)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("blood_group", models.CharField(blank=True, max_length=5, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="DiseaseReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "disease_type",
                    models.CharField(
                        choices=[
                            ("flu", "Influenza (Flu)"),
                            ("covid", "COVID-19"),
                            ("dengue", "Dengue"),
                            ("malaria", "Malaria"),
                            ("cholera", "Cholera"),
                            ("tuberculosis", "Tuberculosis"),
                            ("measles", "Measles"),
                            ("hepatitis", "Hepatitis"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        verbose_name="Disease Type",
                    ),
                ),
                (
                    "affected_area",
                    models.CharField(max_length=255, verbose_name="Affected Area"),
                ),
                (
                    "cases_reported",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Number of Cases",
                    ),
                ),
                (
                    "severity_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="Severity Level",
                    ),
                ),
                (
                    "outbreak_start_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Outbreak Start Date",
                    ),
                ),
                (
                    "additional_info",
                    models.TextField(
                        blank=True, null=True, verbose_name="Additional Information"
                    ),
                ),
                (
                    "reporter_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Reporter Name",
                    ),
                ),
                (
                    "reporter_contact",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Reporter Contact",
                    ),
                ),
                (
                    "is_confirmed",
                    models.BooleanField(
                        default=False, verbose_name="Confirmed Outbreak"
                    ),
                ),
                (
                    "action_taken",
                    models.TextField(
                        blank=True, null=True, verbose_name="Action Taken"
                    ),
                ),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disease_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disease Report",
                "verbose_name_plural": "Disease Reports",
                "ordering": ["-reported_at"],
            },
        ),
        migrations.CreateModel(
            name="HealthEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("visit", "Community Visit"),
                            ("vaccination", "Vaccination Drive"),
                            ("workshop", "Health Workshop"),
                            ("screening", "Health Screening"),
                            ("meeting", "Team Meeting"),
                            ("other", "Other Event"),
                        ],
                        max_length=20,
                        verbose_name="Event Type",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Event Title")),
                ("description", models.TextField(verbose_name="Event Description")),
                ("location", models.CharField(max_length=255, verbose_name="Location")),
                (
                    "start_datetime",
                    models.DateTimeField(verbose_name="Start Date & Time"),
                ),
                ("end_datetime", models.DateTimeField(verbose_name="End Date & Time")),
                (
                    "assigned_to",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Assigned To",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Health Event",
                "verbose_name_plural": "Health Events",
                "ordering": ["start_datetime"],
            },
        ),
        migrations.CreateModel(
            name="PatientRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Patient Name")),
                (
                    "age",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(120),
                        ],
                        verbose_name="Age",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("O", "Other"),
                            ("U", "Unknown"),
                        ],
                        default="U",
                        max_length=1,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Contact Number",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Address"),
                ),
                (
                    "condition",
                    models.CharField(max_length=255, verbose_name="Medical Condition"),
                ),
                (
                    "diagnosis_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Diagnosis Date"
                    ),
                ),
                ("treatment_plan", models.TextField(verbose_name="Treatment Plan")),
                (
                    "medications",
                    models.TextField(blank=True, null=True, verbose_name="Medications"),
                ),
                (
                    "allergies",
                    models.TextField(blank=True, null=True, verbose_name="Allergies"),
                ),
                (
                    "emergency_contact",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Emergency Contact",
                    ),
                ),
                (
                    "emergency_phone",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Emergency Phone",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Additional Notes"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Record",
                "verbose_name_plural": "Patient Records",
                "ordering": ["-created_at"],
            },
        ),
    ]
