# Generated by Django 5.2.5 on 2025-09-13 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientrecord",
            name="citizen",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "citizen"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="citizen_patient_records",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Citizen",
            ),
        ),
    ]
