# Generated by Django 5.2.5 on 2025-09-26 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='CommunityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Alert Subject')),
                ('message', models.TextField(verbose_name='Alert Message')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipients_count', models.PositiveIntegerField(default=0, verbose_name='Number of Recipients')),
                ('sent_successfully', models.PositiveIntegerField(default=0, verbose_name='Sent Successfully')),
                ('sent_failed', models.PositiveIntegerField(default=0, verbose_name='Sent Failed')),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'health_worker'}, on_delete=django.db.models.deletion.CASCADE, related_name='community_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Community Alert',
                'verbose_name_plural': 'Community Alerts',
                'ordering': ['-sent_at'],
            },
        ),
    ]
