# Generated by Django 4.2.23 on 2025-09-26 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userprofile_aadhar_number_communityalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasereport',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved Date'),
        ),
        migrations.AddField(
            model_name='diseasereport',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reports', to=settings.AUTH_USER_MODEL, verbose_name='Approver'),
        ),
        migrations.AddField(
            model_name='diseasereport',
            name='approver_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Approver Comment'),
        ),
        migrations.AddField(
            model_name='diseasereport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Workflow Status'),
        ),
        migrations.AddField(
            model_name='diseasereport',
            name='verified_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verified Date'),
        ),
        migrations.AddField(
            model_name='diseasereport',
            name='verifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_reports', to=settings.AUTH_USER_MODEL, verbose_name='Verifier'),
        ),
        migrations.AddField(
            model_name='diseasereport',
            name='verifier_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Verifier Comment'),
        ),
    ]
