# Generated by Django 4.2.23 on 2025-10-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_diseasereport_approved_date_diseasereport_approver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasereport',
            name='email_notification_sent',
            field=models.BooleanField(default=False, verbose_name='Email Notification Sent'),
        ),
    ]
