# Generated by Django 4.2.23 on 2025-10-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_diseasereport_email_notification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthevent',
            name='email_notification_sent',
            field=models.BooleanField(default=False, verbose_name='Email Notification Sent'),
        ),
    ]
